.TH embedcover 1 "September 6th, 2010"
.SH NAME
embedcover \- embed album covers into music files
.SH SYNOPSIS
\fBembedcover\fR [\fIoptions\fR]
.SH DESCRIPTION
\fBembedcover\fR a command tool to automatically embed album cover images into music files.
.SH OPTIONS
.IP \-\-help,\ \-h
Display help messages.
.IP \-\-recursive,\ \-r
Deal with directories recursively.
.IP \-\-dir=DIRECTORY,\ \-d DIRECTORY
The directory with music files to deal with.
.IP \-\-verbose,\ \-v
Output all messages during the process.
.IP \-\-quiet,\ \-q
Only output errors
.SH AUTHOR
Written by Margaret Wang<pipituliuliu at gmail dot com>.
.PP
Based on mutagen (http://code.google.com/p/mutagen/) by Michael Urman.
.SH COPYRIGHT
Copyright  2010  Free  Software  Foundation, Inc.  License GPLv3+: GNU GPL version 3 or later
